project:
  type: website

website:
  title: "Statistics and Methodology - R package validation"
  page-footer: CC-BY SCTO Statistics and Methodology
  favicon: fig/SCTO_Platforms.png
  navbar:
    title: "SCTO Stats and Methodology - R package validation"
    right:
      # - text: "Home"
      #   href: index.html
      - icon: github
        href: "https://github.com/SwissClinicalTrialOrganisation/pkg_validation"
    background: white
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.html
        title: Home
      - href: sop/policy.qmd
      - section: "SOPs"
        contents:
         - href:
         - href: sop/sop_fn_tests.qmd
         - href: sop/risk_metrics.qmd
      - section: "Work Intructions"
        contents:
          - href: wi/pkg_validation.qmd
          - href: wi/testing.qmd
          - href: wi/review_tests.qmd
          - href: wi/running_tests.qmd
      - href: sop/highlevel_ra.qmd
    # logo: SCTO_Platforms.png

resources:
  - fig/*

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
