project:
  type: website

website:
  title: "Statistics and Methodology - R package validation"
  page-footer: CC-BY SCTO Statistics and Methodology
  favicon: SCTO_Platforms.png
  navbar:
    title: "SCTO Stats and Methodology - R package validation"
    right:
      - text: "Home"
        href: index.html
      - icon: github
        href: "https://github.com/SwissClinicalTrialOrganisation/pkg_validation"
    background: white
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.html
        title: Home
      - section: "Documentation"
        contents:
          - href: policy.qmd
          - href: pkg_validation.qmd
          - href: risk_metrics.qmd
          - href: flow.qmd
          - href: testing.qmd
          - href: running_tests.qmd
    # logo: SCTO_Platforms.png

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
