project:
  type: website

website:
  title: "Statistics and Methodology - Validation Platform"
  page-footer: CC-BY SCTO Statistics and Methodology
  favicon: fig/SCTO_Platforms.png
  navbar:
    title: "SCTO Stats and Methodology - Validation Platform"
    right:
      - icon: github
        href: "https://github.com/SwissClinicalTrialOrganisation/pkg_validation"
    background: white

  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        title: "SCTO Computerized Systems Validation Policy for R"
      - href: sop/policy.qmd


      - section: "SOPs"
        contents:
          - href: sop/sop_pkg_risk_assess.qmd
          - href: sop/sop_pkg_fn_testing.qmd


      - section: "Work Intructions"
        contents:
          - href: wi/pkg_validation.qmd
          - href: wi/testing.qmd
          - href: wi/review_tests.qmd
          - href: wi/running_tests.qmd


      - href: sop/businessproc_ra.qmd
      - href: results/pkgassessment.qmd
      - href: results/pkgtesting.qmd

      - section: "Useful links"
        contents:
         - text: Report a package risk assessment
           href: https://github.com/SwissClinicalTrialOrganisation/validation_platform/issues/new?assignees=&labels=package%2C%3Aalarm_clock%3A+triage+%3Aalarm_clock%3A&projects=&template=new_package.yml&title=%5BPackage+risk+assessment%5D%3A+XXX+version+YYY
           target: "_blank"
         - text: Report a package test report
           href: https://github.com/SwissClinicalTrialOrganisation/validation_platform/issues/new?assignees=&labels=test%2C%3Aalarm_clock%3A+triage+%3Aalarm_clock%3A&projects=&template=new_test.yml&title=%5BPackage+test%5D%3A+XXX+version+YYY
           target: "_blank"
         - text: Package tests repository
           target: "_blank"
           href: https://github.com/SwissClinicalTrialOrganisation/validation_tests
         - text: SCTORvalidation R package
           target: "_blank"
           href: https://swissclinicaltrialorganisation.github.io/SCTORvalidation_Rpackage/
         - text: Give us feedback or ask a question
           target: "_blank"
           href: https://github.com/SwissClinicalTrialOrganisation/validation_platform/discussions

      - href: acknowledge.qmd

    # logo: SCTO_Platforms.png

resources:
  - fig/*

format:
  html:
    theme:
      light: [flatly, style.scss]
      dark: [darkly, style.scss]
    css: [styles.css, style.scss]
    toc: true
