blank_issues_enabled: false
contact_links:
  - name: Anything else:
    url: https://github.com/SwissClinicalTrialOrganisation/pkg_validation/discussions
    about: Please use our Discussion board for anything else
