name: New package validation
description: Add a new package validation report to the repo
title: "[Package validation]: XXX version YYY"
labels: ["package", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this validation report!
  - type: input
    id: contact
    attributes:
      label: Name
      description: What is your name?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: package
    attributes:
      label: What package have you validated?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What version of the package have you validated?
    validations:
      required: true
  - type: checkboxes
    id: pkg_author
    attributes:
      label: Package authors is/are 
      options:
        - well known in the statistical, data-science and R communities
        - have "trusted" status
  - type: markdown
    attributes:
      value: |
        ### Documentation
        This section covers the degree of documentation of the package
  - type: input
    id: pkg_publication
    attributes: 
      label: "If available, access to the publication (e.g. DOI, URL):"
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: checkboxes
    id: terms2
    attributes:
      label: Package validation approach
      description: By submitting this issue, you agree to follow our [package validation approach](https://example.com)
      options:
        - label: I have validated the package according to the SCTO SOP
          required: true


