name: New package validation
description: Add a new package validation report to the repo
title: "[Package validation]: XXX version YYY"
labels: ["package", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this validation report!
  - type: input
    id: contact
    attributes:
      label: Name
      description: What is your name?
      placeholder: ex. Joe Bloggs
    validations:
      required: false
  - type: input
    id: package
    attributes:
      label: What package have you validated?
      description:  <!-- TAGSTART:package -->
      placeholder: enter package name here
    validations:
      required: true
  - type: markdown
    attributes:
      value: | 
        <!-- TAGEND:package -->
  - type: input
    id: version
    attributes:
      label: What version of the package have you validated?
    validations:
      required: true
  - type: input
    id: release_date
    attributes:
      label: When was this package version released?
      description: if available
    validations:
      required: false
  - type: input
    id: package_author
    attributes:
      label: Who authored the package
    validations:
      required: true
  - type: dropdown
    id: maintainer
    attributes:
      label: Package maintainer information available?
      description: Check the DESCRIPTION file. A name and email address should be available.
      options: 
        - Available
        - Unavailable
    validations:
      required: true
  - type: dropdown
    id: purpose
    attributes:
      label: Package purpose
      options:
        - Statistical peer-reviewer
        - Statistical non-peer-reviewer
        - Non-statistical
      default: 0
    validations:
      required: true
  - type: input
    id: nr_dependencies
    attributes: 
      label: Number of dependencies
    validations:
      required: true
  - type: dropdown
    id: on_cran
    attributes:
      label: Package location
      options: 
        - CRAN/bioconductor
        - Other (e.g. github)
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### Documentation
        This section covers the degree of documentation of the package
  - type: dropdown
    id: source_code_documented
    attributes:
      label: Is package source code available and is it well documented?
      options:
        - well documented
        - documented
        - not documented
      description: |
          - explanatory comments in the code are a good sign
          - roxygen comments for internal functions is a good sign
          - well structured code (lines, indentation, readability) is a good sign
          - commented-out 'old' code is a bad sign
          - unavailable code is considered 'non-document'
    validations:
      required: true
  - type: dropdown
    id: community_use
    attributes:
      label: Is the package 'known' in the community? are there 'complaints' in the community (stats.exchange / stackoverﬂow / r-blogs...)? Give a general grade as low/med/high
      options:
        - low
        - medium
        - high
      description: |
          - Serious issues and complaints in the community indicate a high risk
          - Number of reported bugs, and have they been corrected?
    validations:
      required: true
  - type: input
    id: downloads
    attributes: 
      label: Number of downloads in the last 12 months
      description: Using the cranlogs package (TODO: add example code, function in the R package)
    validations:
      required: true
  - type: dropdown
    id: bug_reporting_active
    attributes: 
      label: Bug reporting address is available (in DESCRIPTION) and bugs are resolved quickly
      options:
        - yes, fast response
        - yes, slow response
        - non existant
    validations:
      required: true
