name: New package validation
description: Add a new package validation report to the repo
title: "[Package validation]: XXX version YYY"
labels: ["package", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this validation report!
        Please replace XXX in the issue title with the package name, and YYY with the package version.
        We have developed an R package to assist in filling out this form. It is available via xxxxx
  - type: input
    id: contact
    attributes:
      label: Name
      description: What is your name?
      placeholder: ex. Joe Bloggs
    validations:
      required: false
  - type: dropdown
    id: contact_type
    attributes:
      label: What is your relationship with the SCTO?
      options:
        - SCTO Stats and Methodology platform
        - Other SCTO platform
    validations:
      required: false
  - type: input
    id: package
    attributes:
      label: Name of the package you have validated
      placeholder: e.g. ggplot2
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version number of the package evaluated
      placeholder: e.g. 1.12.3
    validations:
      required: true
  - type: input
    id: release_date
    attributes:
      label: Date of release of the evaluated version of the package
      description: If available. Please use ODBC format - YYYY-MM-DD
      placeholder: YYYY-MM-DD
    validations:
      required: false
  - type: dropdown
    id: package_author
    attributes:
      label: The package author has...
      description: Credentials here refer to affiliation to a university or similar institution
      options:
        - well-known or known credentials
        - credentials
        - no clear credentials or group association
    validations:
      required: true
  - type: dropdown
    id: maintainer
    attributes:
      label: Is there a maintainer listed for the package and are their contact details available?
      description: Check the DESCRIPTION file (or the package page on CRAN). A name and email address should be available.
      options: 
        - Available
        - Unavailable
    validations:
      required: true
  - type: dropdown
    id: purpose
    attributes:
      label: Package purpose
      description: |
        Statistical packages implement statistical or machine learning algorithms.
        Non-statistical packages are used for e.g. reporting.
      options:
        - Statistical; published
        - Statistical; non-published
        - Non-statistical
      default: 0
    validations:
      required: true
  - type: input
    id: nr_dependencies
    attributes: 
      label: Number of dependencies
      description: Use `validation::get_n_deps(pkgname)` in R.
      placeholder: e.g. 15
    validations:
      required: true
  - type: dropdown
    id: on_cran
    attributes:
      label: Is the package on available from CRAN or bioconductor?
      options: 
        - "Yes"
        - "No"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### Documentation
        This section covers the degree of documentation of the package
  - type: dropdown
    id: source_code_documented
    attributes:
      label: Is source code available, accessible and documented (i.e., well-structured and including comments) or is the source code unavailable or not clearly commented.
      options:
        - "Yes"
        - "No"
      description: |
        Source code availability refers to it being in a public repository somewhere. Needing to use R to get to the source code (e.g. by typing a function name without brackets/parentheses) is insufficient.
          - explanatory comments in the code are a good sign
          - roxygen comments for internal functions is a good sign
          - well structured code (lines, indentation, readability) is a good sign
          - commented-out 'old' code is a bad sign
    validations:
      required: true
  - type: input
    id: downloads
    attributes: 
      label: Number of downloads in the last 12 months
      description: |
        Use `validation::get_12month_download_score(pkgname)` in R. 
        Note that download statistics are only available for packages on CRAN or Bioconductor.
  - type: dropdown
    id: bug_reporting_active
    attributes: 
      label: Bug reporting address is available (in DESCRIPTION)
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    id: has_vignettes
    attributes: 
      label: Does the package have one or more vignettes?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    id: has_tests
    attributes: 
      label: Does the package have unit and/or function tests performed by the authors? Are they comprehensive? Are they well documented?
      options:
        - Yes, comprehensive
        - Yes, but not comprehensive
        - "No"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        The answers you've provided will be used to create a final risk score for the package. 
        Thanks for participating in our project. 
