name: New package validation
description: Add a new package validation report to the repo
title: "[Package validation]: XXX version YYY"
labels: ["package", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this validation report!
  - type: input
    id: contact
    attributes:
      label: Name
      description: What is your name?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: package
    attributes:
      label: What package have you validated?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What version of the package have you validated?
    validations:
      required: true
