name: New package validation
description: Add a new package validation report to the repo
title: "[Package validation]: XXX version YYY"
labels: ["package", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this validation report!
  - type: input
    id: contact
    attributes:
      label: Name
      description: What is your name?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: package
    attributes:
      label: What package have you validated?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What version of the package have you validated?
    validations:
      required: true
  - type: dropdown
    id: purpose
    attributes:
      label: Package purpose
      options:
        - Statistical
        - Non-statistical
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: pkg_author
    attributes:
      label: Package authors is/are 
      options:
        - label: well known in the statistical, data-science and R communities
        - label: have "trusted" status
        - label: SCTO member
  - type: markdown
    attributes:
      value: |
        ### Documentation
        This section covers the degree of documentation of the package
  - type: checkboxes
    id: pkg_publication_yn
    attributes:
      label: The package has an associated publication
      options:
        - label: "yes"
        - label: "no"
