name: New package validation
description: Add a new package validation report to the repo
title: "[Package validation]: XXX version YYY"
labels: ["package", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this validation report!
        Please replace XXX in the issue title with the package name, and YYY with the package version.
  - type: input
    id: contact
    attributes:
      label: Name
      description: What is your name?
      placeholder: ex. Joe Bloggs
    validations:
      required: false
  - type: input
    id: package
    attributes:
      label: Name of the package you have validated
      placeholder: e.g. ggplot2
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What version of the package have you validated?
      placeholder: e.g. 1.12.3
    validations:
      required: true
  - type: input
    id: release_date
    attributes:
      label: When was this package version released?
      description: If available. Please use ODBC format - YYYY-MM-DD
      placeholder: YYYY-MM-DD
    validations:
      required: false
  - type: dropdown
    id: package_author
    attributes:
      label: The package author has...
      description: Credentials here refer to affiliation to a university or similar institution
      options:
        - well-known or known credentials
        - credentials
        - no clear credentials or group association
    validations:
      required: true
  - type: dropdown
    id: maintainer
    attributes:
      label: Package maintainer information available?
      description: Check the DESCRIPTION file (or the package page on CRAN). A name and email address should be available.
      options: 
        - Available
        - Unavailable
    validations:
      required: true
  - type: dropdown
    id: purpose
    attributes:
      label: Package purpose
      options:
        - Statistical peer-reviewer
        - Statistical non-peer-reviewer
        - Non-statistical
      default: 0
    validations:
      required: true
  - type: input
    id: nr_dependencies
    attributes: 
      label: Number of dependencies
      description: Use `validation::get_n_deps(pkgname)` in R
      placeholder: e.g. 15
    validations:
      required: true
  - type: dropdown
    id: on_cran
    attributes:
      label: Package location
      options: 
        - CRAN/bioconductor
        - Other (e.g. github)
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### Documentation
        This section covers the degree of documentation of the package
  - type: dropdown
    id: source_code_documented
    attributes:
      label: Is package source code available and is it well documented?
      options:
        - well documented
        - documented
        - not documented
      description: |
          - explanatory comments in the code are a good sign
          - roxygen comments for internal functions is a good sign
          - well structured code (lines, indentation, readability) is a good sign
          - commented-out 'old' code is a bad sign
          - unavailable code is considered 'non-document'
    validations:
      required: true
  - type: dropdown
    id: community_use
    attributes:
      label: Is the package 'known' in the community? 
      description: |
        Are there 'complaints' in the community (stats.exchange / stackoverﬂow / r-blogs...)? 
        Give a general grade as low/med/high
      options:
        - low
        - medium
        - high
      description: |
          - Serious issues and complaints in the community indicate a high risk
          - Number of reported bugs, and have they been corrected?
    validations:
      required: true
  - type: input
    id: downloads
    attributes: 
      label: Number of downloads in the last 12 months
      description: |
        Use `validation::get_12month_download_score(pkgname)` in R. 
        Note that download statistics are only available for packages on CRAN.
  - type: dropdown
    id: bug_reporting_active
    attributes: 
      label: Bug reporting address is available (in DESCRIPTION) and bugs are resolved quickly
      options:
        - yes, fast response
        - yes, slow response
        - non existant
    validations:
      required: true
  - type: dropdown
    id: has_vignettes
    attributes: 
      label: Does the package have vignettes?
      options:
        - One or more
        - It does not
    validations:
      required: true
  - type: dropdown
    id: has_tests
    attributes: 
      label: Does the package have tests?
      options:
        - Yes, comprehensive
        - Yes, but not comprehensive
        - It does not
    validations:
      required: true
  - type: dropdown
    id: final_risk
    attributes: 
      label: Final risk score
      description: here it would have to be a manual calculation, but we could have an action that pulls the info from the issue and calculates it
      options:
        - low
        - medium
        - high
    validations:
      required: true
