on:
  issues:
    types: [opened, edited]

name: Calculate risk

permissions:
  issues: write

jobs:
  render:
    name: Reply to issue
    runs-on: macOS-latest
    env: 
      NUMBER: ${{ github.event.issue.number }}
    steps:
      # - uses: managedkaos/print-env@v1.0
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: Rscript -e 'install.packages(c("jsonlite", "cranlogs", "crayon", "dplyr", "glue", "lubridate", "sessioninfo", "testthat", "rmarkdown", "knitr", "kableExtra", "magrittr", "devtools", "readr", "tidyr"))'
      - name: Install validation
        run: Rscript -e 'install.packages("validation", repos = "https://ctu-bern.r-universe.dev", dependencies = TRUE)'
      - name: Run script to calculate risk and post comment
        run: Rscript -e 'source("resources/calculate_risk.R")'
    
