on:
  issues:
    types: [opened, edited]

name: print env

jobs:
  render:
    name: print env
    runs-on: ubuntu-latest
    steps:
      - uses: managedkaos/print-env@v1.0

  sayHi:
    if: startWith(github.event.issue.title, '[Package validation]')
    runs-on: ubuntu-latest
    steps:
      - name: Say Hi
        run: echo "Hello, World!"
